version = 1

[[analyzers]]
name = "ansible"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "php"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"